default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        exclude: ^(ms_collector/|fake_api_server/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [ --config=ms_sender/pyproject.toml ]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [ pyproject-flake8 ]
        args: [ --config=ms_sender/pyproject.toml ]
        exclude: ^(ms_collector/|fake_api_server/)

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^(ms_collector/|fake_api_server/)

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --keep-runtime-typing]
        exclude: ^(ms_collector/|fake_api_server/)
