"""database creation

Revision ID: 4e7f7b9413f2
Revises:
Create Date: 2024-09-11 13:16:14.520956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e7f7b9413f2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("brand_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="sender",
    )
    op.create_table(
        "property_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["sender.product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sender",
    )
    op.create_table(
        "property",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("property_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_group_id"],
            ["sender.property_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sender",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property", schema="sender")
    op.drop_table("property_group", schema="sender")
    op.drop_table("product", schema="sender")
    # ### end Alembic commands ###
